application:
  port: 8000
  hmac_secret: "very-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.sendgrid.com"
  send_path: "/v3/mail/send"
  sender_email: "saml_test@alt9.co.kr"
  api_key: ""
  timeout_milliseconds: 100000